import type { Frame, Task, TaskStatus } from "./types"

export const defaultFrames: Frame[] = [
  {
    id: "app-setup",
    title: "App Setup & Initial Planning",
    color: "#3B82F6",
    offsetStart: -49,
    offsetEnd: -49,
    description: "Start Here",
  },
  {
    id: "8-weeks",
    title: "Plan, Purge, & Well-Being",
    color: "#10B981",
    offsetStart: -56,
    offsetEnd: -56,
    description: "8 weeks",
  },
  {
    id: "7-weeks",
    title: "7 Weeks: Supplies & Equipment",
    color: "#10B981",
    offsetStart: -49,
    offsetEnd: -49,
    description: "7 weeks",
  },
  {
    id: "6-weeks",
    title: "6 Weeks: Logistics & Records",
    color: "#10B981",
    offsetStart: -42,
    offsetEnd: -42,
    description: "6 weeks",
  },
  {
    id: "5-weeks",
    title: "5 Weeks: Packing",
    color: "#84CC16",
    offsetStart: -35,
    offsetEnd: -35,
    description: "5 weeks",
  },
  {
    id: "4-weeks",
    title: "4 Weeks: Admin & Appointments",
    color: "#84CC16",
    offsetStart: -28,
    offsetEnd: -28,
    description: "4 weeks",
  },
  {
    id: "2-3-weeks",
    title: "2–3 Weeks: Confirmations & Final Prep",
    color: "#EAB308",
    offsetStart: -21,
    offsetEnd: -14,
    description: "3 weeks to 2 weeks",
  },
  {
    id: "1-week",
    title: "1 Week: Home Stretch",
    color: "#F97316",
    offsetStart: -7,
    offsetEnd: -7,
    description: "1 week",
  },
  {
    id: "day-before",
    title: "Day Before Move",
    color: "#F97316",
    offsetStart: -1,
    offsetEnd: -1,
    description: "1 day",
  },
  {
    id: "move-day",
    title: "Move Day",
    color: "#EF4444",
    offsetStart: 0,
    offsetEnd: 0,
    description: "0 days",
  },
  {
    id: "post-move",
    title: "Post-Move",
    color: "#14B8A6",
    offsetStart: 1,
    offsetEnd: 30,
    description: "+1 day to +1 month",
  },
]

export const defaultTasks: Task[] = [
  // App Setup & Initial Planning
  {
    id: "task-1",
    title: "Get Comfortable with the App",
    description: "Familiarize yourself with the moving app features and interface",
    status: "not-started" as TaskStatus,
    defaultFrame: "app-setup",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-2",
    title: "Configure App Settings",
    description: "Set up your preferences, notifications, and account settings",
    status: "not-started" as TaskStatus,
    defaultFrame: "app-setup",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-3",
    title: "Assess Your DIY Move Capacity",
    description: "Evaluate what you can handle yourself vs. what needs professional help",
    status: "not-started" as TaskStatus,
    defaultFrame: "app-setup",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-4",
    title: "Define Spaces & Create Owners",
    description: "Map out rooms and assign responsibility for packing each area",
    status: "not-started" as TaskStatus,
    defaultFrame: "app-setup",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-5",
    title: "Generate & Test Your Move ID",
    description: "Create your unique move identifier and test the system",
    status: "not-started" as TaskStatus,
    defaultFrame: "app-setup",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-6",
    title: "Invite & Onboard Helpers",
    description: "Invite friends and family to help with your move and get them set up in the app",
    status: "not-started" as TaskStatus,
    defaultFrame: "app-setup",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-7",
    title: "Verify Scanning Functionality",
    description: "Test the barcode/QR code scanning features of the app",
    status: "not-started" as TaskStatus,
    defaultFrame: "app-setup",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-8",
    title: "Establish Your Moving Budget",
    description: "Create a comprehensive budget for all moving-related expenses",
    status: "not-started" as TaskStatus,
    defaultFrame: "app-setup",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-9",
    title: "Set Up Your Timeline & Calendar",
    description: "Plan your moving timeline and integrate with your calendar",
    status: "not-started" as TaskStatus,
    defaultFrame: "app-setup",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-10",
    title: "Consider Backup Plans",
    description: "Develop contingency plans for potential moving day issues",
    status: "not-started" as TaskStatus,
    defaultFrame: "app-setup",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Plan, Purge, & Well-Being
  {
    id: "task-11",
    title: "Address the Emotional Side of Moving",
    description: "Prepare mentally for the move and manage stress",
    status: "not-started" as TaskStatus,
    defaultFrame: "8-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-12",
    title: "Declutter Every Room",
    description: "Go through each room and decide what to keep, donate, or discard",
    status: "not-started" as TaskStatus,
    defaultFrame: "8-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "critical",
    checklist: [
      { id: "cl-1", text: "Living room", completed: false },
      { id: "cl-2", text: "Kitchen", completed: false },
      { id: "cl-3", text: "Bedrooms", completed: false },
      { id: "cl-4", text: "Bathrooms", completed: false },
      { id: "cl-5", text: "Garage/Storage", completed: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-13",
    title: "Pay Up Bills & Debts",
    description: "Settle outstanding bills and debts before moving",
    status: "not-started" as TaskStatus,
    defaultFrame: "8-weeks",
    labels: [{ id: "utilities-services", name: "Utilities & Services", color: "#EF4444" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-14",
    title: "Determine Required Truck Size",
    description: "Calculate the size of moving truck needed based on your belongings",
    status: "not-started" as TaskStatus,
    defaultFrame: "8-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-15",
    title: "Research Rental Truck Companies",
    description: "Compare different truck rental companies and their services",
    status: "not-started" as TaskStatus,
    defaultFrame: "8-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-16",
    title: "Gather Quotes for Truck Rentals",
    description: "Get price quotes from multiple truck rental companies",
    status: "not-started" as TaskStatus,
    defaultFrame: "8-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-17",
    title: "Outline Your Packing Strategy",
    description: "Plan your approach to packing different types of items",
    status: "not-started" as TaskStatus,
    defaultFrame: "8-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-18",
    title: "Schedule High-Demand Appointments",
    description: "Book appointments that are difficult to schedule on short notice",
    status: "not-started" as TaskStatus,
    defaultFrame: "8-weeks",
    labels: [{ id: "utilities-services", name: "Utilities & Services", color: "#EF4444" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-19",
    title: "Identify & Plan for Non-Allowable Items",
    description: "Identify items that can't be moved and plan for their disposal",
    status: "not-started" as TaskStatus,
    defaultFrame: "8-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-20",
    title: "Create a Preliminary Floor Plan",
    description: "Plan the layout of furniture in your new home",
    status: "not-started" as TaskStatus,
    defaultFrame: "8-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 7 Weeks: Supplies & Equipment
  {
    id: "task-21",
    title: "Purchase Packing Materials",
    description: "Buy boxes, tape, bubble wrap, and other packing supplies",
    status: "not-started" as TaskStatus,
    defaultFrame: "7-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "high",
    checklist: [
      { id: "cl-6", text: "Moving boxes (various sizes)", completed: false },
      { id: "cl-7", text: "Packing tape", completed: false },
      { id: "cl-8", text: "Bubble wrap", completed: false },
      { id: "cl-9", text: "Markers for labeling", completed: false },
      { id: "cl-10", text: "Packing paper", completed: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-22",
    title: "Source Free Boxes (Optional)",
    description: "Find free boxes from local stores, friends, or online marketplaces",
    status: "not-started" as TaskStatus,
    defaultFrame: "7-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-23",
    title: "Rent or Buy Moving Equipment",
    description: "Secure dollies, straps, and other moving equipment",
    status: "not-started" as TaskStatus,
    defaultFrame: "7-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-24",
    title: "Prep Your Packing Stations",
    description: "Set up designated areas for packing different types of items",
    status: "not-started" as TaskStatus,
    defaultFrame: "7-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-25",
    title: "Begin Selling & Donating Items",
    description: "Start selling or donating items you've decided not to move",
    status: "not-started" as TaskStatus,
    defaultFrame: "7-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-26",
    title: "Be Charitable",
    description: "Donate items to local charities and get donation receipts",
    status: "not-started" as TaskStatus,
    defaultFrame: "7-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 6 Weeks: Logistics & Records
  {
    id: "task-27",
    title: "Reserve Your Moving Truck",
    description: "Book your moving truck rental for the move date",
    status: "not-started" as TaskStatus,
    defaultFrame: "6-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "critical",
    dueDate: new Date(Date.now() + 42 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-28",
    title: "Back Up Digital Files",
    description: "Create backups of important digital files and documents",
    status: "not-started" as TaskStatus,
    defaultFrame: "6-weeks",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-29",
    title: "Organize Vital Documents",
    description: "Gather and organize important documents for easy access",
    status: "not-started" as TaskStatus,
    defaultFrame: "6-weeks",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-30",
    title: "Apply for Parking Permits",
    description: "Get necessary parking permits for moving day",
    status: "not-started" as TaskStatus,
    defaultFrame: "6-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-31",
    title: "Reserve Elevators & Loading Docks",
    description: "Book elevator and loading dock access for both locations",
    status: "not-started" as TaskStatus,
    defaultFrame: "6-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-32",
    title: "Obtain Medical & Prescription Records",
    description: "Get copies of medical records and prescription information",
    status: "not-started" as TaskStatus,
    defaultFrame: "6-weeks",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-33",
    title: "Transfer School Records",
    description: "Arrange for school records to be transferred to new schools",
    status: "not-started" as TaskStatus,
    defaultFrame: "6-weeks",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-34",
    title: "Notify Landlord & Review Lease",
    description: "Give proper notice to landlord and review lease requirements",
    status: "not-started" as TaskStatus,
    defaultFrame: "6-weeks",
    labels: [{ id: "utilities-services", name: "Utilities & Services", color: "#EF4444" }],
    priority: "critical",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-35",
    title: "Finalize Pet Logistics",
    description: "Plan transportation and care arrangements for pets",
    status: "not-started" as TaskStatus,
    defaultFrame: "6-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 5 Weeks: Packing
  {
    id: "task-36",
    title: "Begin Packing Non-Essential Areas",
    description: "Start packing items you won't need in the coming weeks",
    status: "not-started" as TaskStatus,
    defaultFrame: "5-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-37",
    title: "Label & Inventory Every Box",
    description: "Create a detailed inventory system for all packed boxes",
    status: "not-started" as TaskStatus,
    defaultFrame: "5-weeks",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-38",
    title: "Disassemble Large Furniture",
    description: "Take apart furniture that needs to be disassembled for moving",
    status: "not-started" as TaskStatus,
    defaultFrame: "5-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-39",
    title: "Prepare Your Specialty Item Strategy",
    description: "Plan how to pack and move valuable or fragile items",
    status: "not-started" as TaskStatus,
    defaultFrame: "5-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-40",
    title: "Use Up Perishable Items",
    description: "Consume or dispose of perishable food and household items",
    status: "not-started" as TaskStatus,
    defaultFrame: "5-weeks",
    labels: [{ id: "cleaning-maintenance", name: "Cleaning & Maintenance", color: "#059669" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 4 Weeks: Admin & Appointments
  {
    id: "task-41",
    title: "File a Change of Address with USPS",
    description: "Submit change of address form with postal service",
    status: "not-started" as TaskStatus,
    defaultFrame: "4-weeks",
    labels: [{ id: "utilities-services", name: "Utilities & Services", color: "#EF4444" }],
    priority: "critical",
    dueDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-42",
    title: "Update Your Address with Key Institutions",
    description: "Notify banks, insurance, employers, and other important institutions",
    status: "not-started" as TaskStatus,
    defaultFrame: "4-weeks",
    labels: [{ id: "utilities-services", name: "Utilities & Services", color: "#EF4444" }],
    priority: "high",
    checklist: [
      { id: "cl-11", text: "Bank and credit cards", completed: false },
      { id: "cl-12", text: "Insurance companies", completed: false },
      { id: "cl-13", text: "Employer/HR department", completed: false },
      { id: "cl-14", text: "IRS and state tax agencies", completed: false },
      { id: "cl-15", text: "Subscription services", completed: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-43",
    title: "Transfer or Cancel Memberships",
    description: "Handle gym, club, and other membership transfers or cancellations",
    status: "not-started" as TaskStatus,
    defaultFrame: "4-weeks",
    labels: [{ id: "utilities-services", name: "Utilities & Services", color: "#EF4444" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-44",
    title: "Schedule Utility Services",
    description: "Arrange for utilities to be connected at your new home",
    status: "not-started" as TaskStatus,
    defaultFrame: "4-weeks",
    labels: [{ id: "utilities-services", name: "Utilities & Services", color: "#EF4444" }],
    priority: "critical",
    checklist: [
      { id: "cl-16", text: "Electricity", completed: false },
      { id: "cl-17", text: "Gas", completed: false },
      { id: "cl-18", text: "Water/Sewer", completed: false },
      { id: "cl-19", text: "Internet/Cable", completed: false },
      { id: "cl-20", text: "Trash/Recycling", completed: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-45",
    title: "Return All Borrowed Items",
    description: "Return items borrowed from friends, family, or libraries",
    status: "not-started" as TaskStatus,
    defaultFrame: "4-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-46",
    title: "Arrange Childcare & Pet Care for Move Day",
    description: "Organize care for children and pets during the move",
    status: "not-started" as TaskStatus,
    defaultFrame: "4-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-47",
    title: "Schedule Move-Out Repairs & Cleaning",
    description: "Arrange for any needed repairs and professional cleaning",
    status: "not-started" as TaskStatus,
    defaultFrame: "4-weeks",
    labels: [{ id: "cleaning-maintenance", name: "Cleaning & Maintenance", color: "#059669" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-48",
    title: "Plan Your Farewells",
    description: "Organize goodbye gatherings with friends and neighbors",
    status: "not-started" as TaskStatus,
    defaultFrame: "4-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 2–3 Weeks: Confirmations & Final Prep
  {
    id: "task-49",
    title: "Confirm All Reservations",
    description: "Double-check all bookings and reservations for move day",
    status: "not-started" as TaskStatus,
    defaultFrame: "2-3-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-50",
    title: "Measure Critical Pathways",
    description: "Measure doorways, hallways, and stairs at both locations",
    status: "not-started" as TaskStatus,
    defaultFrame: "2-3-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-51",
    title: "Finalize Your Furniture Placement Plan",
    description: "Complete the floor plan for your new home",
    status: "not-started" as TaskStatus,
    defaultFrame: "2-3-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-52",
    title: "Dispose of Hazardous Materials",
    description: "Properly dispose of paint, chemicals, and other hazardous items",
    status: "not-started" as TaskStatus,
    defaultFrame: "2-3-weeks",
    labels: [{ id: "cleaning-maintenance", name: "Cleaning & Maintenance", color: "#059669" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-53",
    title: "Have Your Car Serviced",
    description: "Get your vehicle serviced for the move, especially for long distances",
    status: "not-started" as TaskStatus,
    defaultFrame: "2-3-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-54",
    title: "Plan Your Travel & Truck Route",
    description: "Map out the best route and plan travel logistics",
    status: "not-started" as TaskStatus,
    defaultFrame: "2-3-weeks",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-55",
    title: "Pack All Non-Essential Items",
    description: "Complete packing of all non-essential belongings",
    status: "not-started" as TaskStatus,
    defaultFrame: "2-3-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-56",
    title: 'Pack an "Essentials" Box',
    description: "Pack a box with items you'll need immediately after the move",
    status: "not-started" as TaskStatus,
    defaultFrame: "2-3-weeks",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    checklist: [
      { id: "cl-21", text: "Toiletries and medications", completed: false },
      { id: "cl-22", text: "Change of clothes", completed: false },
      { id: "cl-23", text: "Phone chargers", completed: false },
      { id: "cl-24", text: "Important documents", completed: false },
      { id: "cl-25", text: "Snacks and water", completed: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-57",
    title: "Secure Valuables & Important Documents",
    description: "Pack valuables and documents to carry with you personally",
    status: "not-started" as TaskStatus,
    defaultFrame: "2-3-weeks",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // 1 Week: Home Stretch
  {
    id: "task-58",
    title: "Finalize Plans with Helpers",
    description: "Confirm details with friends/family helping with the move",
    status: "not-started" as TaskStatus,
    defaultFrame: "1-week",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-59",
    title: "Pack Remaining Belongings",
    description: "Pack all remaining items except absolute essentials",
    status: "not-started" as TaskStatus,
    defaultFrame: "1-week",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-60",
    title: "Remove Wall Hangings & Patch Holes",
    description: "Take down pictures and artwork, patch and touch up walls",
    status: "not-started" as TaskStatus,
    defaultFrame: "1-week",
    labels: [{ id: "cleaning-maintenance", name: "Cleaning & Maintenance", color: "#059669" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-61",
    title: "Deep Clean Your Home",
    description: "Thoroughly clean your current home for move-out",
    status: "not-started" as TaskStatus,
    defaultFrame: "1-week",
    labels: [{ id: "cleaning-maintenance", name: "Cleaning & Maintenance", color: "#059669" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-62",
    title: "1 Day Out (Defrost fridge, last items, load personal vehicle)",
    description: "Final day preparations including defrosting refrigerator",
    status: "not-started" as TaskStatus,
    defaultFrame: "1-week",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "high",
    checklist: [
      { id: "cl-26", text: "Defrost and clean refrigerator", completed: false },
      { id: "cl-27", text: "Pack last-minute items", completed: false },
      { id: "cl-28", text: "Load personal vehicle", completed: false },
      { id: "cl-29", text: "Prepare cleaning supplies for move day", completed: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Move Day
  {
    id: "task-63",
    title: "Get a Good Night's Sleep & Start Early",
    description: "Rest well and begin move day activities early",
    status: "not-started" as TaskStatus,
    defaultFrame: "move-day",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "critical",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-64",
    title: "Dress Appropriately",
    description: "Wear comfortable, practical clothing and closed-toe shoes",
    status: "not-started" as TaskStatus,
    defaultFrame: "move-day",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-65",
    title: "Pick Up the Truck",
    description: "Collect the rental truck and inspect it thoroughly",
    status: "not-started" as TaskStatus,
    defaultFrame: "move-day",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "critical",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-66",
    title: "Ensure Safety",
    description: "Maintain safety protocols throughout the moving process",
    status: "not-started" as TaskStatus,
    defaultFrame: "move-day",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "critical",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-67",
    title: "Load the Truck Correctly",
    description: "Load items strategically for safe transport",
    status: "not-started" as TaskStatus,
    defaultFrame: "move-day",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "critical",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-68",
    title: "Final Walkthrough & Security Check",
    description: "Do a final check of the property before leaving",
    status: "not-started" as TaskStatus,
    defaultFrame: "move-day",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "critical",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-69",
    title: "Arrival & Unloading",
    description: "Safely arrive at destination and unload belongings",
    status: "not-started" as TaskStatus,
    defaultFrame: "move-day",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "critical",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-70",
    title: "Post-Unload",
    description: "Complete post-unload tasks and return rental equipment",
    status: "not-started" as TaskStatus,
    defaultFrame: "move-day",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Post-Move
  {
    id: "task-71",
    title: "Check Utilities",
    description: "Verify all utilities are working in your new home",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "utilities-services", name: "Utilities & Services", color: "#EF4444" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-72",
    title: "Scan Boxes",
    description: "Use the app to scan and track your boxes in the new location",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-73",
    title: "Unpack High-Priority Rooms",
    description: "Focus on unpacking essential rooms first",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    checklist: [
      { id: "cl-30", text: "Kitchen essentials", completed: false },
      { id: "cl-31", text: "Bedroom basics", completed: false },
      { id: "cl-32", text: "Bathroom necessities", completed: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-74",
    title: "Tend to Pets",
    description: "Help pets adjust to their new environment",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-75",
    title: "Childproof Home",
    description: "Install safety measures for children in the new home",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "cleaning-maintenance", name: "Cleaning & Maintenance", color: "#059669" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-76",
    title: "Break Down Boxes",
    description: "Flatten and organize empty boxes for disposal or storage",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "cleaning-maintenance", name: "Cleaning & Maintenance", color: "#059669" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-77",
    title: "Update Registrations & Address",
    description: "Complete address changes with government agencies",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "utilities-services", name: "Utilities & Services", color: "#EF4444" }],
    priority: "high",
    checklist: [
      { id: "cl-33", text: "Driver's license", completed: false },
      { id: "cl-34", text: "Vehicle registration", completed: false },
      { id: "cl-35", text: "Voter registration", completed: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-78",
    title: "Establish Healthcare & Schooling",
    description: "Set up healthcare providers and school enrollment",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "utilities-services", name: "Utilities & Services", color: "#EF4444" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-79",
    title: "Secure New Home",
    description: "Install or update security measures in your new home",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "cleaning-maintenance", name: "Cleaning & Maintenance", color: "#059669" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-80",
    title: "Finalize Budget",
    description: "Review and finalize your moving expenses and budget",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-81",
    title: "Explore & Connect",
    description: "Explore your new neighborhood and connect with the community",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-82",
    title: "Throw Housewarming Party",
    description: "Celebrate your new home with friends and family",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-83",
    title: "Review Your DIY Moving Experience",
    description: "Reflect on the moving process and document lessons learned",
    status: "not-started" as TaskStatus,
    defaultFrame: "post-move",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
