import type { Task, Frame } from "./types"

export const defaultFrames: Frame[] = [
  {
    id: "app-setup",
    title: "App Setup & Initial Planning",
    color: "#3B82F6",
    offsetStart: -49,
    offsetEnd: -49,
    description: "Start Here",
  },
  {
    id: "8-weeks",
    title: "Plan, Purge, & Well-Being",
    color: "#10B981",
    offsetStart: -56,
    offsetEnd: -56,
    description: "8 weeks",
  },
  {
    id: "7-weeks",
    title: "7 Weeks: Supplies & Equipment",
    color: "#10B981",
    offsetStart: -49,
    offsetEnd: -49,
    description: "7 weeks",
  },
  {
    id: "6-weeks",
    title: "6 Weeks: Logistics & Records",
    color: "#10B981",
    offsetStart: -42,
    offsetEnd: -42,
    description: "6 weeks",
  },
  {
    id: "5-weeks",
    title: "5 Weeks: Packing",
    color: "#84CC16",
    offsetStart: -35,
    offsetEnd: -35,
    description: "5 weeks",
  },
  {
    id: "4-weeks",
    title: "4 Weeks: Admin & Appointments",
    color: "#84CC16",
    offsetStart: -28,
    offsetEnd: -28,
    description: "4 weeks",
  },
  {
    id: "2-3-weeks",
    title: "2–3 Weeks: Confirmations & Final Prep",
    color: "#EAB308",
    offsetStart: -21,
    offsetEnd: -14,
    description: "3 weeks to 2 weeks",
  },
  {
    id: "1-week",
    title: "1 Week: Home Stretch",
    color: "#F97316",
    offsetStart: -7,
    offsetEnd: -7,
    description: "1 week",
  },
  {
    id: "day-before",
    title: "Day Before Move",
    color: "#F97316",
    offsetStart: -1,
    offsetEnd: -1,
    description: "1 day",
  },
  {
    id: "move-day",
    title: "Move Day",
    color: "#EF4444",
    offsetStart: 0,
    offsetEnd: 0,
    description: "0 days",
  },
  {
    id: "post-move",
    title: "Post-Move",
    color: "#14B8A6",
    offsetStart: 1,
    offsetEnd: 30,
    description: "+1 day to +1 month",
  },
]

export const defaultTasks: Task[] = [
  // App Setup & Initial Planning
  {
    id: "task-1",
    title: "Get Comfortable with the App",
    description: "Familiarize yourself with the moving app features and interface",
    status: "not-started",
    defaultFrame: "app-setup",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-2",
    title: "Configure App Settings",
    description: "Set up your preferences, notifications, and account settings",
    status: "not-started",
    defaultFrame: "app-setup",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-3",
    title: "Assess Your DIY Move Capacity",
    description: "Evaluate what you can handle yourself vs. what needs professional help",
    status: "not-started",
    defaultFrame: "app-setup",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-4",
    title: "Define Spaces & Create Owners",
    description: "Map out rooms and assign responsibility for packing each area",
    status: "not-started",
    defaultFrame: "app-setup",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-5",
    title: "Generate & Test Your Move ID",
    description: "Create your unique move identifier and test the system",
    status: "not-started",
    defaultFrame: "app-setup",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-6",
    title: "Invite & Onboard Helpers",
    description: "Invite friends and family to help with your move and get them set up in the app",
    status: "not-started",
    defaultFrame: "app-setup",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-7",
    title: "Verify Scanning Functionality",
    description: "Test the barcode/QR code scanning features of the app",
    status: "not-started",
    defaultFrame: "app-setup",
    labels: [{ id: "inventory-documentation", name: "Inventory & Documentation", color: "#10B981" }],
    priority: "low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-8",
    title: "Establish Your Moving Budget",
    description: "Create a comprehensive budget for all moving-related expenses",
    status: "not-started",
    defaultFrame: "app-setup",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-9",
    title: "Set Up Your Timeline & Calendar",
    description: "Plan your moving timeline and integrate with your calendar",
    status: "not-started",
    defaultFrame: "app-setup",
    labels: [{ id: "packing-organizing", name: "Packing & Organizing", color: "#8B5CF6" }],
    priority: "high",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task-10",
    title: "Consider Backup Plans",
    description: "Develop contingency plans for potential moving day issues",
    status: "not-started",
    defaultFrame: "app-setup",
    labels: [{ id: "logistics-transportation", name: "Logistics & Transportation", color: "#F59E0B" }],
    priority: "medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]
